version: 2.1
jobs:
  print-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello"
  print-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Say hello"
          command: "echo ,World"
          
workflows:
  say-hello-workflow:
    jobs:
      - print-hello
      - print-World:
          requires:
            - print-hello