version: 2.1
jobs:
  print-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello"

  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Say hello"
          command: "echo ,World"

  print_ENV:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name : "print ENV"
          command : |
                    echo $MY_ENV_VAR
          
workflows:
  say-hello-workflow:
    jobs:
      - print-hello
      - print_world:
          requires:
            - print-hello
      - print_ENV