version: 2.1
commands:
  print_pipeline_id:
    description: "print workflow Id "
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID 
        
      

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          command: "echo Hello World >> ~/output.txt"
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: "cat ~/output.txt"
  print_workflow_ID_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
  when_fail_job: 
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: 
          name: "non-zero failure"
          command: return 1
      - run:
          name: "send to log"
          command: echo "test fails due to non-zero return value"
          when: on_fail

workflows:
  say-hello-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - "save_hello_world_output"
      - print_workflow_ID_job
      - when_fail_job